<?php
/** Template Name: Perspectives & Community */
get_header();
?>

<section class="page-hero page-hero--dark" aria-labelledby="perspectives-title"><div class="container page-hero-grid"><div class="page-hero-copy"><span class="eyebrow reveal">Perspectives &amp; community</span><h1 id="perspectives-title" class="reveal reveal-delay-1">Independent offices.<br><em class="accent-gold">Shared perspective.</em></h1><p class="reveal reveal-delay-2">MCM can act as a bridge between single family offices—creating space for trusted introductions, peer exchange, and a stronger community without selling services or representing other families.</p></div><div class="page-hero-media reveal reveal-delay-2"><img src="<?php echo esc_url( get_template_directory_uri() . '/assets/images/mcm-opportunities.jpg' ); ?>" alt="An open architectural threshold looking toward the Hong Kong harbour horizon" width="1536" height="1024"></div></div></section>

<section class="section--white" aria-labelledby="community-title"><div class="container"><div class="section-heading reveal"><div><span class="eyebrow">Our community role</span><h2 id="community-title">Connecting peers, not acquiring clients</h2></div><p>MCM serves its own family only. Our community activity is limited to helping independent single family offices find one another and exchange relevant experience.</p></div><div class="collaboration-grid"><article class="collaboration-card reveal"><span class="card-index">01</span><h3>Trusted introductions</h3><p>Where there is mutual relevance and consent, we can introduce family-office peers to begin a direct conversation.</p></article><article class="collaboration-card reveal reveal-delay-1"><span class="card-index">02</span><h3>Peer perspectives</h3><p>We welcome non-commercial dialogue around shared questions, long-term thinking, governance, and lessons learned.</p></article><article class="collaboration-card reveal reveal-delay-2"><span class="card-index">03</span><h3>Community connection</h3><p>We hope to strengthen relationships among SFO peers while respecting each office’s privacy, mandate, and independence.</p></article></div></div></section>

<section class="section" aria-labelledby="exchange-title"><div class="container split-feature"><div class="split-feature-media reveal"><img src="<?php echo esc_url( get_template_directory_uri() . '/assets/images/mcm-shared-perspective.jpg' ); ?>" alt="A circular table set for a private exchange of ideas" width="1536" height="1024" loading="lazy"></div><div class="identity-copy reveal reveal-delay-1"><span class="eyebrow">A clear boundary</span><h2 id="exchange-title">Exchange without intermediation.</h2><p>MCM does not advise, manage, arrange transactions for, or represent other families. We do not charge for introductions or community participation.</p><p>Any introduction is simply a connection between independent peers. Each office decides whether and how to continue the conversation and remains responsible for its own review and decisions.</p><a href="<?php echo esc_url( home_url( '/contact/' ) ); ?>" class="text-link">Connect as an SFO peer →</a></div></div></section>

<section class="section--dark" aria-labelledby="principles-title"><div class="container criteria-layout"><div class="criteria-copy reveal"><span class="eyebrow">How exchange works</span><h2 id="principles-title">Private, relevant, reciprocal.</h2><p>We favour thoughtful conversations over broad networking.</p></div><div class="criteria-grid reveal reveal-delay-1"><div class="criterion"><strong>Peer relevance</strong><span>Connections are intended for genuine single family offices and closely relevant participants.</span></div><div class="criterion"><strong>Mutual consent</strong><span>We make introductions only when both sides are comfortable connecting.</span></div><div class="criterion"><strong>No representation</strong><span>MCM does not speak, negotiate, or make commitments for another office.</span></div><div class="criterion"><strong>Independent judgment</strong><span>Every participant retains responsibility for its own diligence and decisions.</span></div></div></div></section>

<section class="cta-band" aria-labelledby="community-cta-title"><div class="container cta-band-content reveal"><span class="eyebrow">Join the conversation</span><h2 id="community-cta-title">Connect with the SFO community.</h2><p>If you represent a single family office and see value in a relevant peer exchange, send us a concise introduction.</p><a href="<?php echo esc_url( home_url( '/contact/' ) ); ?>" class="btn btn-primary">Contact MCM</a></div></section>
<div class="compliance-strip"><div class="container"><p>MCM serves one family and invests its own family capital. Community introductions are not advisory, brokerage, placement, referral, or investment services and do not imply endorsement of any participant or opportunity.</p></div></div>

<?php get_footer(); ?>
